## Setup

The following packages are required to run the analysis. If not already installed, the packages will be installed using `pip`.

In [ ]:
!pip install numpy
!pip install pandas
!pip install scipy
!pip install hmmlearn
!pip install statsmodels
!pip install mpl_scatter_density
!pip install tqdm
!pip install colorama
!pip install pyliftover

In [2]:
# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
from tqdm import tqdm
import statsmodels.api as sm
import scipy.stats as stats
import math
import glob
from pyliftover import LiftOver
import requests
import warnings

# Suppress all warnings to keep the output clean
warnings.filterwarnings("ignore")

## Specify project directories

Define the paths to the data and results directories used in the project.

In [4]:
# Specify the directories containing data and results
data_path = '/oak/stanford/groups/mrivas/projects/wgs-constraint-llm/data/'
results_path = '/oak/stanford/groups/mrivas/projects/wgs-constraint-llm/osthoag/wgs-constraint-llm/results/'

# Specify the paths to the specific data files
gene_annotation_file_path = data_path + 'gencode.v44.basic.annotation.gtf.gz'
scz_variants_file_path = data_path + 'scz.tsv.gz'
constraint_predictions_file_path = results_path + f'HMM_rgc_0.9_over20_chr2_predictions_rgc_wes.tsv.gz'
alpha_missense_file_path = data_path + 'AlphaMissense_hg38.tsv.gz'

## Define helper methods

In [9]:
# Function to calculate effect size and variance for variants
def calculate_effect_size_and_variance(cases_df):
    ALT_AJ = cases_df['ac_case']
    ALT_ExAC = cases_df['ac_ctrl']
    REF_AJ = cases_df['an_case'] - cases_df['ac_case']
    REF_ExAC = cases_df['an_ctrl'] - cases_df['ac_ctrl']

    # Logarithmic transformation of effect size calculation
    cases_df['effect_size'] = np.log(((0.5 + ALT_AJ) * (0.5 + REF_ExAC)) / ((0.5 + REF_AJ) * (0.5 + ALT_ExAC)))
    # Variance calculation for the effect size
    cases_df['var_effect_size'] = (1 / (0.5 + REF_AJ) + 1 / (0.5 + REF_ExAC) + 1 / (0.5 + ALT_AJ) + 1 / (0.5 + ALT_ExAC))
    
    return cases_df

# Initialize liftover object to convert coordinates from hg19 to hg38
lo = LiftOver('hg19', 'hg38')

# Function to apply liftover to a single row
def liftover(row):
    lifted = lo.convert_coordinate(row['chr'], row['pos'])
    if lifted:
        # Return the first lifted coordinate if successful
        return lifted[0][0], int(lifted[0][1])
    else:
        # Return the original chromosome with position 0 if liftover fails
        return row['chr'], 0

## Load Data
This section loads the gene annotation data from a GTF file and extracts relevant information such as gene ID, gene type, gene name, and transcript details. The data is then filtered to include only protein-coding regions.

In [10]:
# Read the GTF file into a pandas DataFrame
gene_df = pd.read_csv(gene_annotation_file_path, sep='\t', comment='#', header=None, 
                      names=['chr', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attribute'], 
                      dtype={'start': int, 'end': int})

# Extract 'gene_id' from attributes
gene_df['gene_id'] = gene_df['attribute'].str.extract(r'gene_id "(.*?)"')

# Extract 'gene_type' from attributes
gene_df['gene_type'] = gene_df['attribute'].str.extract(r'gene_type "(.*?)"')

# Extract 'gene_name' from attributes
gene_df['gene_name'] = gene_df['attribute'].str.extract(r'gene_name "(.*?)"')

# Extract 'transcript_id' from attributes
gene_df['transcript_id'] = gene_df['attribute'].str.extract(r'transcript_id "(.*?)"')

# Extract 'transcript' and 'num' from transcript_id
gene_df[['transcript', 'transcript_num']] = gene_df['transcript_id'].str.split('.', expand=True)

# Extract 'transcript_name' from attributes
gene_df['transcript_name'] = gene_df['attribute'].str.extract(r'transcript_name "(.*?)"')

# Drop the original attribute column
gene_df = gene_df.drop('attribute', axis=1)

# Filter rows for protein-coding regions
gene_df = gene_df[(gene_df['gene_type'] == 'protein_coding') & (gene_df['feature'] == 'CDS')]

# Standardize the gene_id by removing any version numbers (i.e., text after the dot)
gene_df['std_gene_id'] = gene_df['gene_id'].str.split('.').str[0]

# Display the DataFrame
gene_df

,chr,source,feature,start,end,score,strand,frame,gene_id,gene_type,gene_name,transcript_id,transcript,transcript_num,transcript_name,std_gene_id
60,chr1,HAVANA,CDS,65565,65573,.,+,0,ENSG00000186092.7,protein_coding,OR4F5,ENST00000641515.2,ENST00000641515,2,OR4F5-201,ENSG00000186092
63,chr1,HAVANA,CDS,69037,70005,.,+,0,ENSG00000186092.7,protein_coding,OR4F5,ENST00000641515.2,ENST00000641515,2,OR4F5-201,ENSG00000186092
236,chr1,HAVANA,CDS,450743,451678,.,-,0,ENSG00000284733.2,protein_coding,OR4F29,ENST00000426406.4,ENST00000426406,4,OR4F29-201,ENSG00000284733
304,chr1,HAVANA,CDS,685719,686654,.,-,0,ENSG00000284662.2,protein_coding,OR4F16,ENST00000332831.5,ENST00000332831,5,OR4F16-201,ENSG00000284662
524,chr1,HAVANA,CDS,924432,924948,.,+,0,ENSG00000187634.13,protein_coding,SAMD11,ENST00000616016.5,ENST00000616016,5,SAMD11-209,ENSG00000187634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998488,chrM,ENSEMBL,CDS,10470,10763,.,+,0,ENSG00000212907.2,protein_coding,MT-ND4L,ENST00000361335.1,ENST00000361335,1,MT-ND4L-201,ENSG00000212907
1998495,chrM,ENSEMBL,CDS,10760,12137,.,+,0,ENSG00000198886.2,protein_coding,MT-ND4,ENST00000361381.2,ENST00000361381,2,MT-ND4-201,ENSG00000198886
1998509,chrM,ENSEMBL,CDS,12337,14145,.,+,0,ENSG00000198786.2,protein_coding,MT-ND5,ENST00000361567.2,ENST00000361567,2,MT-ND5-201,ENSG00000198786
1998515,chrM,ENSEMBL,CDS,14149,14673,.,-,0,ENSG00000198695.2,protein_coding,MT-ND6,ENST00000361681.2,ENST00000361681,2,MT-ND6-201,ENSG00000198695
1998523,chrM,ENSEMBL,CDS,14747,15887,.,+,0,ENSG00000198727.2,protein_coding,MT-CYB,ENST00000361789.2,ENST00000361789,2,MT-CYB-201,ENSG00000198727

## Load and Filter Schizophrenia Variant Data
This section reads in the schizophrenia variant data, splits the chromosome and position information, filters out unwanted chromosomes and variant types, and merges it with the gene annotation data to include gene names.

In [ ]:
# Read the schizophrenia variant data into a DataFrame
scz_variant_results_df = pd.read_csv(scz_variants_file_path, sep='\t')

# Split the locus into chromosome and position, and convert the position to an integer
scz_variant_results_df[['chr', 'pos']] = scz_variant_results_df['locus'].str.split(':', expand=True)
scz_variant_results_df['chr'] = 'chr' + scz_variant_results_df['chr'].astype(str)
scz_variant_results_df['pos'] = pd.to_numeric(scz_variant_results_df['pos'], errors='coerce').fillna(0).astype(int)

filter_consequence_list = [
    "3_prime_UTR_variant",
    "5_prime_UTR_variant",
    "coding_sequence_variant",
    "downstream_gene_variant",
    "intergenic_variant",
    "intron_variant",
    "mature_miRNA_variant",
     "non_coding_transcript_exon_variant",
    "non_coding_transcript_variant",
    "null",
    "synonymous_variant",
   "upstream_gene_variant",
    "splice_region_variant",
    "stop_retained_variant",
    "protein_altering_variant"
]

pLoF_consequence_list = [
    'stop_gained',
    'splice_acceptor_variant',
    'splice_donor_variant',
    'frameshift_variant'
]

# Apply the liftover function to each row in the DataFrame
scz_variant_results_df[['chr', 'pos']] = scz_variant_results_df.apply(liftover, axis=1, result_type='expand')

# Filter out rows related to sex chromosomes and unrelated consequences
scz_variant_results_df = scz_variant_results_df[(scz_variant_results_df['chr'] != "chrX") &
                                                (scz_variant_results_df['chr'] != "chrY") &
                                                (scz_variant_results_df['chr'] != "chrMT")]
scz_variant_results_df = scz_variant_results_df[~scz_variant_results_df['consequence'].isin(filter_consequence_list)]
scz_variant_results_df = scz_variant_results_df[~scz_variant_results_df['consequence'].isna()]

# Merge the filtered variants with gene names from the gene annotation data
scz_variant_results_df = pd.merge(scz_variant_results_df, gene_df[['std_gene_id', 'gene_name']].drop_duplicates(), left_on='gene_id', right_on='std_gene_id', how='left').drop('std_gene_id', axis=1)

scz_variant_results_df

## Filter Variants for Analysis
Further filtering of variants is done to include only those with a total allele count (ac_ctrl + ac_case) of 5 or less, and with non-zero allele numbers in both cases and controls.

In [ ]:
# Filter variants dataframe for analysis
variants_df = scz_variant_results_df

# Filter variants where the sum of allele counts in cases and controls is less than or equal to 5
# and where both case and control allele numbers are non-zero
variants_df = variants_df[(variants_df['ac_ctrl'] + variants_df['ac_case'] <= 5) &
                          (variants_df['an_case'] > 0) &
                          (variants_df['an_ctrl'] > 0)]

## Load Constraint Predictions
Load saved HMM predictions for constraint data, which will be used in building the unified model.

In [ ]:
# Load in saved predictions for the constraint dataset
constraint_predictions_df = pd.read_csv(constraint_predictions_file_path, sep='\t')

# Display the DataFrame
constraint_predictions_df

## Load Missense Pathogenicity Data
Load and preprocess missense pathogenicity data, including extracting transcript details and renaming columns for consistency.

In [ ]:
# Read the missense pathogenicity data into a pandas DataFrame
alpha_missense_df = pd.read_csv(alpha_missense_file_path, sep='\t', header=3)

# Rename columns to standard labels
alpha_missense_df.rename(columns={"#CHROM": "chr", "POS": "pos", "REF": "ref", "ALT": 'alt'}, inplace=True)

# Extract 'transcript' and 'transcript_num' from transcript_id
alpha_missense_df[['transcript', 'transcript_num']] = alpha_missense_df['transcript_id'].str.split('.', expand=True)

# Display the DataFrame
alpha_missense_df

## Build Unified Constraint, Pathogenicity, and pLoF Model
This section creates a unified model that integrates constraint predictions, pathogenicity predictions, and loss-of-function (pLoF) indicators to assess the association with schizophrenia.

In [12]:
# Subset the constraint predictions to include only relevant columns
constraint_predictions_df = constraint_predictions_df[['chr', 'pos', 'prob_0']]

# Group by chromosome and position, and find the maximum 'am_pathogenicity' value
max_am_pathogenicity_df = alpha_missense_df.groupby(['chr', 'pos'])['am_pathogenicity'].max().reset_index()

# Copy the variants dataframe to create a pLoF-specific dataframe
pLoF_ind_variants_df = variants_df

# Create an indicator column for pLoF variants (1 for pLoF, 0 otherwise)
pLoF_ind_variants_df['pLoF_ind'] = (variants_df['consequence'] == "pLoF").astype('int32')

# Subset the pLoF dataframe to include only useful columns
pLoF_ind_variants_df = pLoF_ind_variants_df[['chr', 'pos', 'gene_id', 'gene_name', 'group', 'ac_case', 'an_case', 'ac_ctrl', 'an_ctrl', 'pLoF_ind']]

# Calculate effect size and variance for pLoF variants
pLoF_ind_variants_df = calculate_effect_size_and_variance(pLoF_ind_variants_df)

# Merge constraint predictions, pathogenicity predictions, and pLoF variants based on chromosome and position
constraint_pathogenicity_pLoF_df = pd.merge(pLoF_ind_variants_df, pd.merge(constraint_predictions_df, max_am_pathogenicity_df, on=['chr', 'pos'], how='inner'), on=['chr', 'pos'], how='inner')

# Save the merged dataframe to a compressed CSV file for further analysis
constraint_pathogenicity_pLoF_df.to_csv(results_path + f"constraint_am_scz_pLoF.tsv.gz", index=False, compression='gzip', sep='\t')

# Display the DataFrame
constraint_pathogenicity_pLoF_df

,chr,pos,gene_id,gene_name,group,ac_case,an_case,ac_ctrl,an_ctrl,pLoF_ind,effect_size,var_effect_size,prob_0,am_pathogenicity
0,chr1,925946,ENSG00000187634,SAMD11,meta,0,48496,3,194644,0,-0.556242,2.285740,0.000050,0.9876
1,chr1,925948,ENSG00000187634,SAMD11,meta,0,48496,1,194644,0,0.291066,2.666692,0.000040,0.9460
2,chr1,925952,ENSG00000187634,SAMD11,EUR (exomes),1,17748,0,38148,0,1.863854,2.666749,0.000050,0.9687
3,chr1,925952,ENSG00000187634,SAMD11,meta,1,48496,0,194644,0,2.488316,2.666692,0.000050,0.9687
4,chr1,925957,ENSG00000187634,SAMD11,AFR (genomes),1,4490,0,2340,0,0.447236,2.667317,0.009844,0.8327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5418790,chr22,50769528,ENSG00000079974,RABL2B,meta,0,48496,1,194644,0,0.291066,2.666692,0.015377,0.2788
5418791,chr22,50775792,ENSG00000079974,RABL2B,EST (genomes),0,522,1,4562,0,1.068170,2.668800,0.383440,0.4733
5418792,chr22,50775792,ENSG00000079974,RABL2B,meta,0,48496,1,194644,0,0.291066,2.666692,0.383440,0.4733
5418793,chr22,50775820,ENSG00000079974,RABL2B,EUR-N (exomes),4,14554,1,22374,0,1.528864,0.889002,0.396517,0.9987
5418794,chr22,50775845,ENSG00000079974,RABL2B,meta,0,48496,3,194644,0,-0.556242,2.285740,0.003953,0.9852

## Meta-Regression Model for Schizophrenia
This section builds a meta-regression model for each gene, incorporating constraint, pathogenicity, and pLoF information. The results are saved and displayed for further analysis.

In [6]:
# Read the data from the file containing constraint, pathogenicity, and pLoF information for schizophrenia genes
constraint_pathogenicity_pLoF_df = pd.read_csv(results_path + f'constraint_am_scz_pLoF.tsv.gz', sep='\t')

In [8]:
constraint_pathogenicity_pLoF_df

,chr,pos,gene_id,gene_name,group,ac_case,an_case,ac_ctrl,an_ctrl,pLoF_ind,effect_size,var_effect_size,prob_0,am_pathogenicity
0,chr1,925946,ENSG00000187634,SAMD11,meta,0,48496,3,194644,0,-0.556242,2.285740,0.000050,0.9876
1,chr1,925948,ENSG00000187634,SAMD11,meta,0,48496,1,194644,0,0.291066,2.666692,0.000040,0.9460
2,chr1,925952,ENSG00000187634,SAMD11,EUR (exomes),1,17748,0,38148,0,1.863854,2.666749,0.000050,0.9687
3,chr1,925952,ENSG00000187634,SAMD11,meta,1,48496,0,194644,0,2.488316,2.666692,0.000050,0.9687
4,chr1,925957,ENSG00000187634,SAMD11,AFR (genomes),1,4490,0,2340,0,0.447236,2.667317,0.009844,0.8327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5418790,chr22,50769528,ENSG00000079974,RABL2B,meta,0,48496,1,194644,0,0.291066,2.666692,0.015377,0.2788
5418791,chr22,50775792,ENSG00000079974,RABL2B,EST (genomes),0,522,1,4562,0,1.068170,2.668800,0.383440,0.4733
5418792,chr22,50775792,ENSG00000079974,RABL2B,meta,0,48496,1,194644,0,0.291066,2.666692,0.383440,0.4733
5418793,chr22,50775820,ENSG00000079974,RABL2B,EUR-N (exomes),4,14554,1,22374,0,1.528864,0.889002,0.396517,0.9987
5418794,chr22,50775845,ENSG00000079974,RABL2B,meta,0,48496,3,194644,0,-0.556242,2.285740,0.003953,0.9852

In [13]:
# Read the data from the file containing constraint, pathogenicity, and pLoF information for schizophrenia genes
constraint_pathogenicity_pLoF_df = pd.read_csv(results_path + f'constraint_am_scz_pLoF.tsv.gz', sep='\t')

# Initialize a list to store the results of the meta-regression model
meta_model_results = []

# Compute the negative log of the probabilities for constraint and pathogenicity to use as predictors
input_df = constraint_pathogenicity_pLoF_df
input_df[['log_constraint', 'log_pathogenicity']] = -np.log(1-input_df[['prob_0', 'am_pathogenicity']])

# Group the data by gene_id, gene_name, and group to build models for each gene separately
grouped_gene_data = input_df.groupby(['gene_id', 'gene_name', 'group'])

# Loop over each gene group and build a meta-regression model
for gene_key, gene_data in tqdm(grouped_gene_data, desc="Processing genes", unit="gene"):
    gene_id, gene_name, group = gene_key
    
    # Prepare the design matrix (X) and response variable (y) for the regression model
    X = sm.add_constant(gene_data[['log_constraint', 'log_pathogenicity', 'pLoF_ind']])
    y = gene_data['effect_size']

    # Weights are the inverse of the variance of the effect size
    weights = 1 / gene_data['var_effect_size']

    try:
        # Fit a weighted least squares (WLS) regression model
        model = sm.WLS(y, X, weights=weights, missing='drop').fit()
        
        # Append relevant results to the meta_model_results list
        meta_model_results.append({
            'gene_id': gene_id,
            'gene_name': gene_name,
            'group': group,
            'p_constraint': model.pvalues['log_constraint'],
            'p_pathogenicity': model.pvalues['log_pathogenicity'],
            'p_pLoF': model.pvalues['pLoF_ind'],
            'p_const': model.pvalues['const'],
            'p_unified': model.f_pvalue
        })

    except Exception as e:
        # Handle any errors that arise during model fitting
#         print(f"Error processing gene {gene_name} in group {group}: {e}")
        pass

# Convert the list of results to a DataFrame for further analysis
unified_model_df = pd.DataFrame(meta_model_results)

# Save the DataFrame containing p-values from the meta-regression models to a compressed CSV file
unified_model_df.to_csv(results_path + "schizophrenia_unified_model_pvalues.tsv", index=False, sep='\t')

# Display the contents of the DataFrame
unified_model_df

Processing genes:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████▊ | 185603/187765 [14:42<00:10, 210.39gene/s]

,gene_id,gene_name,group,p_constraint,p_pathogenicity,p_pLoF,p_const,p_unified
0,ENSG00000000419,DPM1,AFR (genomes),0.451656,0.266461,NaN,0.250178,0.419736
1,ENSG00000000419,DPM1,AMR (exomes),0.654983,0.648871,NaN,0.576296,0.803001
2,ENSG00000000419,DPM1,EAS (exomes),0.356055,0.675121,NaN,0.782929,0.562411
3,ENSG00000000419,DPM1,EUR (exomes),0.331273,0.012301,NaN,0.000020,0.035529
4,ENSG00000000419,DPM1,EUR-N (exomes),0.484493,0.208346,NaN,0.059904,0.375240
...,...,...,...,...,...,...,...,...
150756,ENSG00000273217,ENSG00000273217,EUR (exomes),NaN,NaN,NaN,NaN,NaN
150757,ENSG00000273217,ENSG00000273217,meta,NaN,NaN,NaN,NaN,NaN
150758,ENSG00000273274,ZBTB8B,AFR (genomes),0.386409,0.743476,NaN,0.302428,0.678464
150759,ENSG00000273274,ZBTB8B,EST (genomes),NaN,NaN,NaN,NaN,NaN
150760,ENSG00000273274,ZBTB8B,meta,0.263176,0.664155,NaN,0.000107,0.523143

In [5]:
# Read the saved model results
unified_model_df = pd.read_csv(results_path + "schizophrenia_unified_model_pvalues.tsv", sep='\t')

# Filter the DataFrame for significant p-values or specific gene names for closer examination
filter_mask = (unified_model_df['p_unified'] < 1e-4) | (unified_model_df['p_constraint'] < 1e-4)
gene_name_mask = (unified_model_df['gene_name'] == 'CACNA1A')
gene_name_mask2 = (unified_model_df['gene_name'].str.contains('CACNA1'))
gene_name_mask3 = (unified_model_df['gene_name'].isin(['POLG', 'DYNC1H1', 'GLRA1', 'PTEN', 'BRAT1', 'ALDH7A1', 'GAL']))

# Display the filtered DataFrame sorted by the unified p-value
pd.set_option('display.max_rows', 700)
unified_model_df[filter_mask].sort_values('p_unified')

,gene_id,gene_name,group,p_constraint,p_pathogenicity,p_pLoF,p_const,p_unified
66142,ENSG00000139323,POC1B,AMR (exomes),0.000000e+00,NaN,NaN,0.000000e+00,0.000000e+00
73801,ENSG00000145242,EPHA5,AFR (exomes),0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00
146111,ENSG00000225921,NOL7,EUR-N (exomes),0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00
121952,ENSG00000180917,CMTR2,FIN (exomes),0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00
66968,ENSG00000139971,ARMH4,FIN (exomes),NaN,0.000000e+00,NaN,0.000000e+00,0.000000e+00
96411,ENSG00000164729,SLC35G3,FIN (exomes),NaN,NaN,NaN,0.000000e+00,0.000000e+00
65864,ENSG00000139160,ETFBKMT,AFR (genomes),0.000000e+00,NaN,NaN,0.000000e+00,0.000000e+00
9033,ENSG00000068024,HDAC4,FIN (exomes),0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00
9952,ENSG00000070915,SLC12A3,ASJ (exomes),9.799758e-21,5.123587e-01,NaN,3.417305e-13,3.143347e-20
138071,ENSG00000198010,DLGAP2,EST (genomes),1.633922e-16,2.904133e-03,NaN,1.111800e-23,3.031055e-17
105638,ENSG00000169359,SLC33A1,EAS (exomes),1.286520e-16,1.186551e-16,NaN,1.378368e-16,1.286489e-16
31235,ENSG00000109475,RPL34,EUR-N (exomes),1.713941e-16,6.389536e-15,NaN,1.770878e-16,1.512822e-16
117021,ENSG00000176715,ACSF3,ASJ (exomes),2.577710e-16,2.361285e-16,NaN,5.192815e-16,2.362399e-16
59845,ENSG00000135540,NHSL1,EST (genomes),8.470665e-17,2.674300e-16,NaN,7.841772e-17,2.673411e-16
124611,ENSG00000183036,PCP4,EUR-N (exomes),2.506742e-16,2.272487e-16,NaN,2.430250e-16,3.368460e-16
56937,ENSG00000133627,ACTR3B,EST (genomes),1.531623e-14,4.721475e-16,NaN,1.055771e-15,5.912277e-16
90291,ENSG00000162231,NXF1,AFR (exomes),3.867876e-16,4.736291e-16,NaN,3.139225e-16,6.074642e-16
69039,ENSG00000141505,ASGR1,AFR (exomes),3.169936e-16,6.558243e-16,NaN,2.953708e-16,6.546144e-16
52348,ENSG00000130024,PHF10,EAS (exomes),4.644998e-16,1.129778e-13,NaN,5.134536e-16,6.803069e-16
68826,ENSG00000141404,GNAL,EUR-N (exomes),1.062819e-15,5.766783e-16,NaN,1.085958e-15,7.395284e-16
118186,ENSG00000177595,PIDD1,FIN (genomes),3.006577e-15,8.326736e-16,NaN,1.650630e-15,7.467944e-16
130311,ENSG00000186847,KRT14,AFR (exomes),7.109674e-16,8.763031e-16,NaN,4.068556e-16,8.762220e-16
124349,ENSG00000182899,RPL35A,AMR (exomes),4.661065e-15,4.444035e-16,NaN,1.465947e-15,1.034705e-15
97129,ENSG00000165076,PRSS37,EST (genomes),1.584666e-15,8.796799e-16,NaN,3.025352e-16,1.307254e-15
5608,ENSG00000048740,CELF2,ASJ (exomes),2.809015e-15,9.049352e-16,NaN,7.683944e-16,1.340126e-15
69802,ENSG00000142192,APP,FIN (exomes),8.741220e-16,8.728216e-02,NaN,1.644913e-16,2.336632e-15
45001,ENSG00000122375,OPN4,ASJ (exomes),8.657001e-15,1.795331e-15,NaN,1.533498e-15,2.574697e-15
70805,ENSG00000143164,DCAF6,EST (genomes),1.793006e-15,2.936486e-15,NaN,1.771259e-15,2.930458e-15
55595,ENSG00000132581,SDF2,EST (genomes),2.330663e-15,3.347136e-15,NaN,2.315653e-15,3.315450e-15
55387,ENSG00000132466,ANKRD17,AFR (exomes),3.665872e-15,6.281423e-01,NaN,3.850729e-15,6.107460e-15
21154,ENSG00000100890,PRORP,FIN (exomes),3.200561e-15,4.542701e-01,NaN,8.353422e-16,6.953960e-15
76542,ENSG00000148153,INIP,EAS (exomes),3.618731e-14,7.810087e-14,NaN,4.095092e-14,1.029925e-14
59846,ENSG00000135540,NHSL1,meta,7.574395e-15,1.048383e-14,NaN,5.920330e-15,1.102360e-14
138343,ENSG00000198125,MB,AMR (exomes),8.707716e-15,2.868633e-14,NaN,7.753508e-15,1.153195e-14
140289,ENSG00000198914,POU3F3,meta,8.228795e-15,5.626578e-14,NaN,9.527038e-12,1.272694e-14
41439,ENSG00000118579,MED28,AMR (exomes),2.115472e-14,9.054126e-01,NaN,1.107739e-13,1.355533e-14
73438,ENSG00000144840,RABL3,AMR (exomes),3.311715e-14,1.341629e-14,NaN,4.079374e-14,1.507614e-14
89953,ENSG00000161955,TNFSF13,EUR (exomes),1.052365e-14,3.578699e-14,NaN,1.753196e-14,1.648558e-14
46051,ENSG00000123453,SARDH,EST (genomes),8.679505e-15,5.632017e-01,NaN,6.268027e-17,2.080114e-14
150052,ENSG00000259494,MRPL46,EST (genomes),7.700641e-14,2.225893e-14,NaN,2.526212e-14,2.610440e-14
124824,ENSG00000183172,SMDT1,AMR (exomes),7.178753e-14,2.986617e-14,NaN,1.647437e-13,3.780295e-14
112455,ENSG00000173214,MFSD4B,AFR (exomes),3.753548e-14,3.266114e-11,NaN,2.843125e-14,5.457752e-14
116915,ENSG00000176595,KBTBD11,AFR (genomes),9.493255e-14,1.509115e-13,NaN,1.445778e-13,8.043514e-14
13661,ENSG00000082014,SMARCD3,EAS (exomes),7.497415e-14,1.539294e-11,NaN,1.272449e-13,9.272269e-14
69743,ENSG00000142173,COL6A2,EST (genomes),4.168831e-14,8.850947e-01,NaN,3.128468e-17,1.080154e-13
107756,ENSG00000170605,OR9K2,EST (genomes),2.098109e-13,1.673411e-07,NaN,3.849030e-13,2.414276e-13
40252,ENSG00000117298,ECE1,AFR (exomes),3.343786e-13,3.198230e-01,NaN,1.425948e-12,4.194689e-13
17526,ENSG00000092853,CLSPN,AFR (exomes),1.319054e-13,8.195873e-01,NaN,3.812849e-13,4.279131e-13
18773,ENSG00000099875,MKNK2,AMR (exomes),2.421949e-13,6.271224e-01,NaN,3.786602e-09,5.706912e-13
126949,ENSG00000184708,EIF4ENIF1,AFR (exomes),1.429676e-13,6.429008e-02,NaN,1.042350e-13,6.167596e-13
63427,ENSG00000137693,YAP1,AMR (exomes),1.123376e-12,4.747004e-01,NaN,3.314166e-11,9.938564e-13
81237,ENSG00000152932,RAB3C,EAS (exomes),6.560546e-13,6.557428e-13,NaN,6.561096e-13,1.028651e-12
51998,ENSG00000129473,BCL2L2,EUR-N (exomes),3.913793e-13,4.632068e-01,NaN,2.853132e-12,1.252268e-12
69682,ENSG00000142089,IFITM3,AMR (exomes),1.344522e-12,8.492767e-01,NaN,5.843093e-12,2.849509e-12
78033,ENSG00000149488,TMC2,ASJ (exomes),1.694821e-12,3.751236e-01,NaN,3.790250e-10,2.881026e-12
51598,ENSG00000129048,ACKR4,EUR (exomes),7.465935e-12,7.457500e-12,NaN,7.480962e-12,1.156135e-11
132861,ENSG00000188677,PARVB,AFR (genomes),6.112064e-12,5.662428e-01,NaN,1.943602e-09,1.422599e-11
61892,ENSG00000136802,LRRC8A,FIN (exomes),7.983315e-11,2.428649e-01,NaN,4.999939e-12,2.947949e-11
136969,ENSG00000197532,OR6Y1,EAS (exomes),1.217684e-11,4.606892e-01,NaN,4.288271e-11,3.225527e-11
125148,ENSG00000183463,URAD,EUR (exomes),4.820195e-11,1.718150e-01,NaN,7.600237e-09,5.705240e-11
73098,ENSG00000144647,POMGNT2,EST (genomes),3.042578e-11,8.396161e-01,NaN,1.847870e-12,5.732883e-11
24412,ENSG00000104129,DNAJC17,AFR (genomes),4.013605e-11,7.880864e-02,NaN,1.105087e-10,6.005971e-11
105712,ENSG00000169398,PTK2,EST (genomes),2.116359e-11,3.971393e-01,NaN,3.258374e-13,6.193290e-11
63515,ENSG00000137727,ARHGAP20,FIN (exomes),4.588006e-11,5.102267e-01,NaN,2.992380e-16,6.204480e-11
42364,ENSG00000119685,TTLL5,AFR (exomes),2.069555e-11,4.258429e-01,NaN,1.714879e-10,6.431199e-11
137392,ENSG00000197721,CR1L,FIN (exomes),2.976064e-11,6.095623e-01,NaN,1.282060e-13,7.149921e-11
42411,ENSG00000119698,PPP4R4,EST (genomes),4.729258e-11,5.157629e-01,NaN,4.273407e-14,7.506666e-11
121262,ENSG00000180251,SLC9A4,FIN (exomes),2.597705e-11,4.804774e-01,NaN,2.363656e-11,8.738269e-11
116737,ENSG00000176422,SPRYD4,AMR (exomes),4.497165e-11,6.412705e-01,NaN,2.024543e-08,1.251494e-10
39896,ENSG00000116981,NT5C1A,EST (genomes),1.757820e-10,3.765691e-02,NaN,2.470161e-12,1.612850e-10
96787,ENSG00000164916,FOXK1,EST (genomes),7.623482e-11,4.468317e-01,NaN,3.639821e-13,1.624277e-10
145941,ENSG00000223443,USP17L2,EST (genomes),1.829355e-09,1.379896e-01,NaN,4.736176e-11,1.628661e-10
68964,ENSG00000141458,NPC1,EST (genomes),8.058451e-11,3.072911e-01,NaN,5.250732e-14,1.684065e-10
84550,ENSG00000156502,SUPV3L1,AFR (exomes),6.815017e-11,5.781804e-01,NaN,2.474499e-10,2.127961e-10
132969,ENSG00000188760,TMEM198,AMR (exomes),8.426666e-11,1.907613e-01,NaN,2.162017e-07,2.132644e-10
78098,ENSG00000149527,PLCH2,AFR (exomes),7.873949e-11,7.627600e-01,NaN,2.102819e-09,2.304469e-10
23545,ENSG00000103196,CRISPLD2,ASJ (exomes),1.722473e-10,6.711416e-01,NaN,7.561280e-08,3.015506e-10
78490,ENSG00000149929,HIRIP3,AFR (exomes),1.488121e-10,8.442569e-03,NaN,3.934715e-09,3.627896e-10
43616,ENSG00000120738,EGR1,AFR (exomes),1.199085e-10,2.286497e-02,NaN,2.793390e-09,3.705628e-10
82997,ENSG00000154781,CCDC174,AFR (exomes),1.791457e-10,5.695182e-01,NaN,1.291027e-11,4.092250e-10
79849,ENSG00000151632,AKR1C2,AMR (exomes),2.874294e-10,5.968739e-01,NaN,7.124184e-08,6.352460e-10
22783,ENSG00000102699,PARP4,AFR (exomes),2.287941e-10,6.393601e-01,NaN,7.702610e-10,6.406316e-10
119400,ENSG00000178607,ERN1,EST (genomes),1.908437e-10,8.792239e-01,NaN,2.743487e-11,6.822866e-10
43515,ENSG00000120693,SMAD9,ASJ (exomes),4.794582e-10,7.483403e-01,NaN,2.929129e-07,9.481123e-10
30133,ENSG00000108511,HOXB6,AFR (genomes),3.125786e-10,2.619742e-07,NaN,2.990531e-08,9.764475e-10
88360,ENSG00000160293,VAV2,ASJ (exomes),6.176377e-09,5.560793e-01,NaN,4.584631e-05,1.254808e-09
16959,ENSG00000091262,ABCC6,AFR (exomes),8.957209e-01,2.218352e-01,NaN,1.135998e-190,1.385948e-09
57013,ENSG00000133687,TMTC1,FIN (genomes),6.674940e-10,7.827940e-01,NaN,2.372252e-09,1.504175e-09
68625,ENSG00000141252,VPS53,FIN (exomes),1.855480e-09,2.776146e-01,NaN,7.166139e-12,1.520744e-09
21879,ENSG00000101280,ANGPT4,FIN (exomes),6.692621e-10,4.183786e-01,NaN,4.223266e-10,1.769194e-09
24307,ENSG00000103995,CEP152,AFR (exomes),5.998166e-10,1.762772e-01,NaN,9.689305e-10,1.812144e-09
70084,ENSG00000142530,GARIN5A,AMR (exomes),1.557769e-04,9.123267e-01,NaN,7.677168e-07,2.384434e-09
56453,ENSG00000133083,DCLK1,EST (genomes),1.757451e-09,7.060122e-01,NaN,1.367566e-09,2.392429e-09
3639,ENSG00000023330,ALAS1,EST (genomes),1.319234e-09,3.886842e-01,NaN,5.962238e-12,2.558996e-09
16951,ENSG00000091181,IL5RA,AFR (genomes),1.013859e-09,9.862379e-01,NaN,2.154478e-10,2.572839e-09
109329,ENSG00000171481,OR1L3,AMR (exomes),2.880935e-09,1.968907e-01,NaN,4.516614e-05,2.703449e-09
119563,ENSG00000178773,CPNE7,FIN (exomes),1.024123e-09,2.293352e-02,NaN,1.031742e-09,3.006804e-09
68301,ENSG00000140961,OSGIN1,EST (genomes),1.321745e-09,3.045692e-05,NaN,1.685792e-10,3.283601e-09
99622,ENSG00000166377,ATP9B,AFR (exomes),1.252778e-09,2.321258e-03,NaN,1.087729e-08,3.369612e-09
22944,ENSG00000102854,MSLN,AFR (exomes),1.974376e-09,4.109572e-01,NaN,6.132016e-09,3.723331e-09
63750,ENSG00000137824,RMDN3,AFR (exomes),2.388731e-09,7.285923e-01,NaN,1.587578e-08,3.804573e-09
9538,ENSG00000070019,GUCY2C,AFR (exomes),2.371123e-09,7.963959e-01,NaN,8.979351e-09,3.865594e-09
16364,ENSG00000089876,DHX32,FIN (exomes),2.580702e-09,2.610591e-01,NaN,6.851285e-10,4.615626e-09
46787,ENSG00000124216,SNAI1,AFR (genomes),2.407673e-06,9.974050e-02,NaN,1.989807e-07,4.874748e-09
32749,ENSG00000111012,CYP27B1,AMR (exomes),1.405457e-09,9.424834e-01,NaN,1.337107e-05,5.378087e-09
111025,ENSG00000172349,IL16,EST (genomes),1.891913e-09,5.970606e-01,NaN,1.283676e-09,7.116182e-09
5668,ENSG00000049192,ADAMTS6,EST (genomes),3.562673e-09,4.212815e-01,NaN,5.598548e-10,7.147478e-09
76491,ENSG00000148110,MFSD14B,AFR (exomes),3.988426e-09,6.825532e-01,NaN,2.040091e-08,7.535633e-09
4461,ENSG00000035403,VCL,EST (genomes),6.182444e-09,4.915391e-01,NaN,4.618919e-09,9.196786e-09
31042,ENSG00000109184,DCUN1D4,EAS (exomes),5.127980e-09,5.175393e-01,NaN,7.532134e-09,1.021270e-08
100422,ENSG00000166801,FAM111A,FIN (exomes),2.562885e-08,4.470682e-01,NaN,1.840604e-09,1.044124e-08
46911,ENSG00000124257,NEURL2,EST (genomes),6.833117e-09,3.147439e-01,NaN,2.347273e-08,1.061183e-08
39397,ENSG00000116670,MAD2L2,AFR (genomes),8.078124e-09,9.711405e-02,NaN,1.139808e-07,1.086934e-08
109360,ENSG00000171490,RSL1D1,AFR (exomes),6.801878e-09,2.316758e-02,NaN,6.335777e-08,1.105196e-08
149936,ENSG00000258986,TMEM179,EUR (exomes),5.248719e-09,5.678385e-01,NaN,1.458808e-06,1.340512e-08
24202,ENSG00000103811,CTSH,AMR (exomes),5.862644e-09,7.857782e-01,NaN,1.697849e-06,1.340529e-08
12533,ENSG00000078618,NRDC,FIN (exomes),6.238913e-09,8.493728e-01,NaN,1.877214e-11,1.650908e-08
87091,ENSG00000159189,C1QC,EST (genomes),8.025260e-09,6.856300e-01,NaN,1.346258e-08,1.651522e-08
2195,ENSG00000010319,SEMA3G,EST (genomes),7.531060e-09,2.888797e-01,NaN,9.499205e-09,1.697318e-08
145892,ENSG00000221989,OR2A2,AFR (exomes),2.779615e-08,7.875846e-01,NaN,8.363163e-08,1.798851e-08
112229,ENSG00000173068,BNC2,AFR (exomes),7.567085e-02,1.573754e-01,NaN,1.490074e-159,1.893186e-08
50990,ENSG00000128487,SPECC1,AFR (exomes),2.534871e-07,7.721621e-01,NaN,7.510016e-09,1.896488e-08
105173,ENSG00000169105,CHST14,AMR (exomes),1.391334e-08,3.517219e-01,NaN,2.754653e-08,2.052123e-08
11815,ENSG00000076356,PLXNA2,EST (genomes),7.359933e-09,2.976535e-02,NaN,5.049898e-09,2.127079e-08
120111,ENSG00000179148,ALOXE3,EST (genomes),1.079611e-08,3.085158e-01,NaN,6.928125e-08,2.478269e-08
6870,ENSG00000058335,RASGRF1,FIN (exomes),1.168767e-08,8.801617e-01,NaN,2.489420e-12,2.676296e-08
49203,ENSG00000126217,MCF2L,EST (genomes),7.798556e-01,1.023228e-08,NaN,3.932896e-10,2.684468e-08
139133,ENSG00000198554,WDHD1,AFR (exomes),8.112134e-09,1.331668e-01,NaN,2.797770e-08,2.820065e-08
3825,ENSG00000025770,NCAPH2,AMR (exomes),6.122171e-09,4.130267e-01,NaN,1.353624e-06,2.876523e-08
138866,ENSG00000198400,NTRK1,FIN (exomes),2.279826e-07,5.108964e-01,NaN,5.261777e-10,3.421740e-08
97127,ENSG00000165076,PRSS37,AMR (exomes),2.222967e-08,5.647731e-03,NaN,5.383654e-08,3.580790e-08
94969,ENSG00000164116,GUCY1A1,AFR (exomes),1.677088e-08,9.134382e-02,NaN,9.263176e-08,3.664872e-08
26474,ENSG00000105486,LIG1,AFR (exomes),1.784595e-08,4.494187e-03,NaN,1.913113e-07,3.712013e-08
24462,ENSG00000104147,OIP5,FIN (exomes),2.025384e-08,3.216603e-02,NaN,2.772627e-08,3.758319e-08
73756,ENSG00000145214,DGKQ,EST (genomes),2.394924e-08,5.787260e-01,NaN,6.057216e-09,4.143303e-08
14531,ENSG00000085274,MYNN,FIN (exomes),2.821337e-08,6.280358e-01,NaN,7.688256e-10,4.596444e-08
34414,ENSG00000112280,COL9A1,EST (genomes),3.803682e-08,5.252567e-01,NaN,5.027165e-09,4.765097e-08
61083,ENSG00000136197,C7orf25,FIN (exomes),9.759512e-08,4.797355e-01,NaN,3.673516e-10,4.819877e-08
37690,ENSG00000115306,SPTBN1,AFR (exomes),6.784446e-02,1.000000e+00,NaN,1.710234e-131,5.306489e-08
6333,ENSG00000054523,KIF1B,ASJ (exomes),1.997865e-08,4.952523e-01,NaN,1.962473e-03,5.363028e-08
41183,ENSG00000118307,DNAI7,AFR (exomes),2.996707e-08,5.145446e-01,NaN,5.234525e-07,5.393680e-08
22849,ENSG00000102763,VWA8,EST (genomes),2.359117e-08,4.671005e-01,NaN,1.097420e-08,6.243750e-08
54778,ENSG00000131969,ABHD12B,AMR (exomes),6.458743e-07,2.790034e-01,NaN,1.731818e-05,6.552182e-08
17002,ENSG00000091436,MAP3K20,EST (genomes),2.083014e-08,7.688606e-01,NaN,1.173142e-08,6.632773e-08
54476,ENSG00000131711,MAP1B,AFR (exomes),2.188394e-08,2.459564e-01,NaN,2.571125e-11,6.760728e-08
87817,ENSG00000159871,LYPD5,EUR-N (exomes),1.425323e-07,3.932969e-06,NaN,1.799579e-07,7.352098e-08
96497,ENSG00000164756,SLC30A8,AFR (exomes),8.195573e-07,5.582697e-02,NaN,7.005764e-07,7.852886e-08
150099,ENSG00000260272,ENSG00000260272,EST (genomes),5.600647e-08,7.441771e-01,NaN,2.889091e-08,8.010230e-08
144739,ENSG00000214097,SMCO1,AMR (exomes),4.342722e-08,5.480310e-02,NaN,2.553343e-08,8.042313e-08
62334,ENSG00000136940,PDCL,AMR (exomes),3.857391e-08,6.471809e-01,NaN,1.628903e-06,8.217535e-08
45402,ENSG00000122735,DNAI1,AFR (exomes),1.034199e-07,7.691358e-01,NaN,1.945452e-07,8.484439e-08
14336,ENSG00000084444,FAM234B,EST (genomes),3.743672e-08,8.970209e-03,NaN,4.346598e-08,8.539793e-08
94634,ENSG00000164049,FBXW12,AFR (exomes),2.247503e-07,2.885440e-08,NaN,5.583067e-07,9.442321e-08
93618,ENSG00000163684,RPP14,EAS (exomes),1.211066e-06,1.144473e-07,NaN,5.879423e-08,9.501782e-08
82802,ENSG00000154556,SORBS2,ASJ (exomes),4.926393e-08,6.122293e-01,NaN,1.487106e-04,1.013068e-07
63527,ENSG00000137745,MMP13,EST (genomes),9.586647e-08,8.377824e-03,NaN,7.024258e-08,1.058376e-07
81414,ENSG00000153064,BANK1,FIN (exomes),8.597567e-08,3.936218e-01,NaN,3.054436e-07,1.183240e-07
98074,ENSG00000165655,ZNF503,FIN (exomes),6.272366e-08,2.232908e-01,NaN,2.889348e-08,1.235624e-07
10416,ENSG00000072422,RHOBTB1,EST (genomes),5.584872e-08,6.762479e-01,NaN,2.158561e-08,1.265489e-07
45625,ENSG00000122971,ACADS,EST (genomes),5.175371e-08,1.559170e-01,NaN,1.709140e-10,1.379669e-07
96461,ENSG00000164744,SUN3,FIN (exomes),1.407707e-07,3.309257e-01,NaN,1.057015e-07,1.391343e-07
47538,ENSG00000124772,CPNE5,EST (genomes),3.152534e-07,3.224261e-01,NaN,4.766081e-07,1.479535e-07
57119,ENSG00000133800,LYVE1,EST (genomes),1.182990e-07,8.432544e-02,NaN,2.565366e-07,1.524680e-07
85130,ENSG00000157131,C8A,AFR (exomes),8.070690e-08,3.469841e-01,NaN,4.830057e-07,1.606678e-07
29629,ENSG00000108018,SORCS1,EST (genomes),1.348822e-07,6.787326e-02,NaN,1.103870e-09,1.633662e-07
6906,ENSG00000058673,ZC3H11A,AFR (exomes),9.978705e-08,2.543829e-02,NaN,2.238687e-06,1.657239e-07
104192,ENSG00000168556,ING2,EUR-N (exomes),3.983060e-07,4.655517e-01,NaN,7.826869e-07,1.663306e-07
130300,ENSG00000186834,HEXIM1,EST (genomes),7.925326e-08,5.932328e-01,NaN,9.908603e-09,1.699289e-07
80050,ENSG00000151746,BICD1,FIN (exomes),1.876559e-02,7.067691e-08,NaN,4.498198e-10,1.724956e-07
127773,ENSG00000185220,PGBD2,FIN (exomes),6.113682e-08,1.180277e-01,NaN,4.663153e-08,1.784774e-07
85894,ENSG00000157933,SKI,EST (genomes),6.484767e-08,5.098135e-01,NaN,4.638412e-08,1.881281e-07
132147,ENSG00000188171,ZNF626,AFR (exomes),7.641110e-08,8.406128e-06,NaN,4.371813e-08,1.957699e-07
79777,ENSG00000151575,TEX9,EAS (exomes),7.474932e-08,3.397931e-01,NaN,3.032494e-07,1.986269e-07
66469,ENSG00000139597,N4BP2L1,AMR (exomes),1.023518e-07,8.602101e-03,NaN,6.745381e-06,2.093062e-07
8174,ENSG00000065457,ADAT1,AFR (exomes),9.906492e-08,5.747535e-01,NaN,1.140077e-06,2.248812e-07
32817,ENSG00000111087,GLI1,FIN (genomes),1.609062e-06,3.702686e-01,NaN,8.628405e-07,2.265327e-07
131734,ENSG00000187848,P2RX2,AFR (exomes),2.085348e-01,1.008794e-07,NaN,8.309464e-07,2.342390e-07
5456,ENSG00000047621,C12orf4,FIN (exomes),1.547656e-05,1.437574e-01,NaN,3.580255e-09,2.380007e-07
102077,ENSG00000167608,TMC4,AFR (exomes),1.533647e-07,9.193965e-01,NaN,4.463006e-08,2.506568e-07
110169,ENSG00000171865,RNASEH1,AFR (exomes),1.334982e-07,3.041948e-01,NaN,5.861081e-07,2.572020e-07
77448,ENSG00000148942,SLC5A12,AFR (exomes),1.442258e-07,3.980755e-01,NaN,1.209354e-06,2.592281e-07
79602,ENSG00000151458,ANKRD50,ASJ (exomes),1.278688e-07,3.951197e-01,NaN,4.373273e-05,2.637385e-07
30176,ENSG00000108551,RASD1,AFR (genomes),9.792911e-08,1.054019e-01,NaN,4.635838e-06,2.662242e-07
84822,ENSG00000156858,PRR14,EST (genomes),1.632646e-07,8.904444e-01,NaN,2.923834e-07,2.708546e-07
45157,ENSG00000122512,PMS2,FIN (exomes),1.313028e-07,3.824846e-01,NaN,1.085908e-08,2.743961e-07
48619,ENSG00000125815,CST8,AMR (exomes),1.466740e-07,9.468688e-01,NaN,5.265637e-05,2.828974e-07
26688,ENSG00000105610,KLF1,AMR (exomes),1.542661e-07,8.228203e-02,NaN,1.400115e-05,2.829711e-07
106412,ENSG00000169862,CTNND2,AFR (exomes),9.972700e-08,8.802440e-01,NaN,1.435807e-05,2.839829e-07
40831,ENSG00000117751,PPP1R8,AFR (genomes),1.267315e-07,1.785145e-01,NaN,3.765234e-06,2.931173e-07
40573,ENSG00000117560,FASLG,AMR (exomes),5.225497e-07,3.696997e-01,NaN,2.636870e-07,3.061593e-07
43539,ENSG00000120696,KBTBD7,FIN (exomes),1.506761e-07,9.364822e-01,NaN,3.249441e-10,3.343461e-07
147646,ENSG00000243232,PCDHAC2,EST (genomes),1.844501e-07,1.739081e-05,NaN,1.007357e-07,3.377852e-07
129071,ENSG00000185989,RASA3,EST (genomes),1.543890e-07,6.338544e-01,NaN,1.707586e-07,3.521705e-07
70216,ENSG00000142623,PADI1,AFR (exomes),1.797770e-07,9.973049e-01,NaN,2.808766e-06,3.590708e-07
13989,ENSG00000083290,ULK2,FIN (exomes),1.737913e-07,7.978151e-01,NaN,1.209907e-08,3.619819e-07
52158,ENSG00000129667,RHBDF2,FIN (exomes),2.013689e-07,3.360438e-02,NaN,4.073593e-08,3.721436e-07
36940,ENSG00000114745,GORASP1,EST (genomes),1.983377e-02,4.313504e-07,NaN,7.432789e-11,3.850205e-07
148826,ENSG00000253797,UTP14C,EST (genomes),2.664126e-07,3.325974e-01,NaN,4.294266e-07,3.929943e-07
83620,ENSG00000155561,NUP205,EST (genomes),1.052726e-07,8.097277e-01,NaN,8.393308e-11,4.105103e-07
57997,ENSG00000134365,CFHR4,AFR (exomes),1.919901e-07,4.787727e-01,NaN,4.006917e-10,4.282068e-07
24028,ENSG00000103544,VPS35L,FIN (exomes),1.946360e-07,9.157271e-01,NaN,4.245238e-08,4.407255e-07
143379,ENSG00000206181,ELOA2,AFR (exomes),3.082949e-06,9.979668e-08,NaN,3.068950e-01,4.426936e-07
89931,ENSG00000161940,BCL6B,AFR (exomes),2.448622e-07,5.816913e-01,NaN,2.449227e-07,4.627043e-07

In [7]:
# filter_mask = (unified_model_df['p_comb'] < 1e-4) | (unified_model_df['p_value_overall'] < 1e-4)
filter_mask = (unified_model_df['p_unified'] < 1e-4) | (unified_model_df['p_constraint'] < 1e-4)
group_mask = (unified_model_df['group'] == 'DBS') | (unified_model_df['group'] == 'SWE')
gene_name_mask = (unified_model_df['gene_name'] == 'SLC2A1')

pd.set_option('display.max_rows', 550)
unified_model_df[filter_mask].sort_values('p_comb')

,gene_id,gene_name,group,p_prob_0,p_pathogenicity,p_const,p_overall,p_pLoF,p_comb
91053,ENSG00000163104,SMARCAD1,EST (genomes),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.026751e-01,0.000000e+00
138210,ENSG00000198914,POU3F3,meta,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.994571e-01,0.000000e+00
104788,ENSG00000169660,HEXD,EST (genomes),0.000000e+00,NaN,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
88414,ENSG00000161265,U2AF1L4,EST (genomes),NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00
82579,ENSG00000155393,HEATR3,EST (genomes),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
63750,ENSG00000138134,STAMBPL1,FIN (exomes),NaN,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
18715,ENSG00000099917,MED15,FIN (exomes),NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00
41085,ENSG00000118655,DCLRE1B,EST (genomes),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
133573,ENSG00000196792,STRN3,FIN (exomes),NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
122339,ENSG00000182667,NTM,AMR (exomes),NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00
19329,ENSG00000100170,SLC5A1,FIN (exomes),NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00
97693,ENSG00000166037,CEP57,FIN (exomes),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
1121,ENSG00000006459,KDM7A,FIN (exomes),NaN,0.000000e+00,0.000000e+00,0.000000e+00,2.848611e-01,0.000000e+00
147661,ENSG00000261701,HPR,EST (genomes),NaN,NaN,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
30596,ENSG00000109079,TNFAIP1,FIN (exomes),NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00
75032,ENSG00000147421,HMBOX1,EST (genomes),0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
86008,ENSG00000159131,GART,EST (genomes),NaN,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
143791,ENSG00000225921,NOL7,EUR-N (exomes),3.758725e-16,3.765447e-16,4.031434e-16,3.765447e-16,NaN,3.765447e-16
30951,ENSG00000109475,RPL34,EUR-N (exomes),3.815599e-16,7.427386e-16,6.680563e-16,3.807185e-16,NaN,3.807185e-16
122664,ENSG00000182899,RPL35A,AMR (exomes),5.463002e-16,2.203276e-16,1.988465e-16,5.146790e-16,NaN,5.146790e-16
95975,ENSG00000165076,PRSS37,EST (genomes),8.797495e-16,5.257086e-16,1.926634e-16,7.883036e-16,NaN,7.883036e-16
136012,ENSG00000198010,DLGAP2,EST (genomes),9.886649e-16,8.182195e-03,5.956640e-21,9.385719e-16,NaN,9.385719e-16
17383,ENSG00000092820,EZR,FIN (exomes),5.441912e-16,1.583629e-01,1.427384e-17,7.743243e-16,3.116280e-02,9.992007e-16
68301,ENSG00000141505,ASGR1,AFR (exomes),7.125276e-16,1.033328e-15,4.905463e-16,1.031256e-15,NaN,1.031256e-15
122923,ENSG00000183036,PCP4,EUR-N (exomes),1.192402e-15,1.094059e-15,1.149665e-15,1.622465e-15,NaN,1.622465e-15
44580,ENSG00000122375,OPN4,ASJ (exomes),7.132973e-15,1.415904e-15,1.188711e-15,2.031682e-15,NaN,2.031682e-15
5576,ENSG00000048740,CELF2,ASJ (exomes),1.100198e-14,1.487571e-15,1.284456e-15,2.202891e-15,NaN,2.202891e-15
70049,ENSG00000143164,DCAF6,EST (genomes),2.226688e-15,2.344295e-15,2.115699e-15,2.318895e-15,NaN,2.318895e-15
56349,ENSG00000133627,ACTR3B,EST (genomes),3.172770e-13,2.400009e-15,4.131473e-15,2.982299e-15,NaN,2.982299e-15
89241,ENSG00000162231,NXF1,AFR (exomes),3.494930e-15,4.194912e-15,3.224854e-15,5.380359e-15,NaN,5.380359e-15
136281,ENSG00000198125,MB,AMR (exomes),4.527748e-15,1.755164e-14,4.493253e-15,6.914146e-15,NaN,6.914146e-15
115780,ENSG00000176945,MUC20,meta,1.147213e-15,1.137251e-15,1.355833e-15,1.137281e-15,1.655626e-01,6.994405e-15
104336,ENSG00000169359,SLC33A1,EAS (exomes),4.266890e-16,3.930248e-16,4.566581e-16,4.266802e-16,1.000000e+00,1.554312e-14
103224,ENSG00000168754,FAM178B,EUR-N (exomes),1.677666e-15,9.680185e-16,2.271302e-15,1.512435e-15,3.941183e-01,2.153833e-14
80320,ENSG00000152932,RAB3C,EAS (exomes),2.390800e-14,2.247752e-14,2.249237e-14,3.526998e-14,NaN,3.526998e-14
19049,ENSG00000100077,GRK3,FIN (exomes),1.130437e-14,6.238750e-15,3.269844e-15,9.396501e-15,1.057348e-01,3.530509e-14
68090,ENSG00000141404,GNAL,EUR-N (exomes),4.875234e-14,8.918318e-16,1.052506e-15,1.143293e-15,1.000000e+00,4.052314e-14
115399,ENSG00000176595,KBTBD11,AFR (genomes),2.847272e-13,1.252826e-13,3.053570e-13,6.677399e-14,NaN,6.677399e-14
106409,ENSG00000170605,OR9K2,EST (genomes),7.637322e-14,5.653873e-08,1.561076e-13,8.167120e-14,NaN,8.167120e-14
20995,ENSG00000100890,PRORP,FIN (exomes),4.026175e-14,4.896350e-01,1.355939e-14,8.639936e-14,NaN,8.639936e-14
34230,ENSG00000112335,SNX3,EUR (exomes),2.102534e-15,1.725574e-15,2.323567e-15,2.524456e-15,1.000000e+00,8.737455e-14
72659,ENSG00000144840,RABL3,AMR (exomes),3.042379e-15,2.608597e-15,6.778051e-15,2.928644e-15,1.000000e+00,1.009193e-13
111026,ENSG00000173214,MFSD4B,AFR (exomes),8.418655e-14,7.472681e-11,6.999323e-14,1.250345e-13,NaN,1.250345e-13
9890,ENSG00000070915,SLC12A3,ASJ (exomes),2.492608e-15,4.702663e-01,8.578954e-09,5.134827e-15,1.000000e+00,1.740830e-13
96827,ENSG00000165629,ATP5F1C,AMR (exomes),1.241710e-14,1.510342e-14,1.239129e-14,1.940040e-14,3.061315e-01,2.005063e-13
67894,ENSG00000141252,VPS53,FIN (exomes),4.428039e-15,1.500699e-02,8.966430e-16,9.065875e-15,1.000000e+00,3.022027e-13
13573,ENSG00000082014,SMARCD3,EAS (exomes),6.868164e-13,8.405203e-11,1.703026e-12,5.088762e-13,NaN,5.088762e-13
62769,ENSG00000137693,YAP1,AMR (exomes),6.877101e-13,4.218216e-01,5.896860e-11,1.142464e-12,NaN,1.142464e-12
68936,ENSG00000142089,IFITM3,AMR (exomes),1.036518e-12,4.528364e-01,7.493207e-12,2.239794e-12,NaN,2.239794e-12
58542,ENSG00000135164,DMTF1,EST (genomes),8.844333e-14,7.788384e-11,8.603415e-14,1.347033e-13,1.000000e+00,4.126699e-12
106383,ENSG00000170579,DLGAP1,FIN (exomes),9.396367e-13,3.891722e-01,3.754785e-12,1.849351e-12,2.002950e-01,1.097322e-11
125203,ENSG00000184708,EIF4ENIF1,AFR (exomes),4.308428e-12,1.739216e-01,1.216569e-10,1.896255e-11,NaN,1.896255e-11
25076,ENSG00000104859,CLASRP,EST (genomes),1.541775e-11,3.098262e-01,6.273862e-11,4.399837e-11,NaN,4.399837e-11
39863,ENSG00000117298,ECE1,AFR (exomes),3.552961e-11,2.931546e-01,6.713252e-10,5.526912e-11,NaN,5.526912e-11
123432,ENSG00000183463,URAD,EUR (exomes),5.563285e-11,1.721650e-01,1.225364e-08,5.920941e-11,NaN,5.920941e-11
45626,ENSG00000123453,SARDH,EST (genomes),1.450708e-12,7.166084e-01,5.181132e-14,2.275159e-12,1.000000e+00,6.326983e-11
135355,ENSG00000197721,CR1L,FIN (exomes),3.274521e-11,7.336618e-01,2.176660e-13,8.163554e-11,NaN,8.163554e-11
77171,ENSG00000149488,TMC2,ASJ (exomes),4.740507e-12,2.640836e-01,1.495148e-09,6.587008e-12,1.000000e+00,1.761756e-10
24199,ENSG00000104129,DNAJC17,AFR (genomes),2.133225e-10,3.198978e-01,1.437016e-09,2.152012e-10,NaN,2.152012e-10
68226,ENSG00000141458,NPC1,EST (genomes),1.400128e-10,1.838102e-01,1.899597e-13,2.890649e-10,NaN,2.890649e-10
17412,ENSG00000092853,CLSPN,AFR (exomes),1.220376e-10,8.272158e-01,9.755466e-10,3.894028e-10,NaN,3.894028e-10
117401,ENSG00000178222,RNF212,AMR (exomes),7.614975e-11,4.613081e-01,1.175668e-10,8.764375e-11,2.237430e-01,5.030862e-10
61257,ENSG00000136802,LRRC8A,FIN (exomes),5.427489e-10,3.425807e-01,2.009824e-10,5.565669e-10,NaN,5.565669e-10
43107,ENSG00000120693,SMAD9,ASJ (exomes),4.548399e-10,4.830802e-01,3.267932e-07,8.573347e-10,NaN,8.573347e-10
18651,ENSG00000099875,MKNK2,AMR (exomes),1.515074e-11,5.640554e-01,1.146381e-06,3.899630e-11,1.000000e+00,9.736422e-10
23351,ENSG00000103196,CRISPLD2,ASJ (exomes),5.883752e-10,7.449932e-01,3.391583e-07,1.027854e-09,NaN,1.027854e-09
18458,ENSG00000099381,SETD1A,meta,3.134949e-01,2.514202e-01,8.446946e-25,2.538004e-01,1.767910e-10,1.113990e-09
87339,ENSG00000160293,VAV2,ASJ (exomes),8.252598e-10,9.551631e-01,2.425243e-04,1.526071e-09,NaN,1.526071e-09
83582,ENSG00000156502,SUPV3L1,AFR (exomes),7.667257e-10,5.156059e-01,1.500258e-08,2.393372e-09,NaN,2.393372e-09
55867,ENSG00000133083,DCLK1,EST (genomes),1.843343e-09,6.677925e-01,1.868691e-09,2.427411e-09,NaN,2.427411e-09
62857,ENSG00000137727,ARHGAP20,FIN (exomes),2.436728e-09,5.694303e-01,2.570858e-14,2.594715e-09,NaN,2.594715e-09
95263,ENSG00000164715,LMTK2,AFR (exomes),1.000000e+00,3.754918e-02,2.627447e-146,2.601198e-09,NaN,2.601198e-09
49806,ENSG00000127586,CHTF18,meta,4.404206e-10,4.555819e-04,4.637488e-10,6.911496e-10,1.575987e-01,2.607688e-09
54818,ENSG00000132466,ANKRD17,AFR (exomes),2.210045e-09,9.491048e-01,6.776332e-08,3.571730e-09,NaN,3.571730e-09
22768,ENSG00000102854,MSLN,AFR (exomes),1.950545e-09,3.900084e-01,9.071026e-09,3.710127e-09,NaN,3.710127e-09
95652,ENSG00000164916,FOXK1,EST (genomes),2.215227e-09,2.079915e-01,9.112365e-11,3.897091e-09,NaN,3.897091e-09
130918,ENSG00000188677,PARVB,AFR (genomes),1.707724e-10,8.262379e-01,1.094055e-06,3.138245e-10,5.494797e-01,4.049063e-09
68997,ENSG00000142173,COL6A2,EST (genomes),7.371730e-11,5.399461e-01,1.518590e-12,1.855551e-10,1.000000e+00,4.343413e-09
69055,ENSG00000142192,APP,FIN (exomes),1.424145e-10,3.181158e-01,8.423631e-11,2.369546e-10,1.000000e+00,5.488615e-09
113996,ENSG00000175390,EIF3F,AMR (exomes),2.181658e-09,6.945540e-05,9.932902e-07,5.747636e-09,NaN,5.747636e-09
131388,ENSG00000188994,ZNF292,EUR (exomes),2.137514e-10,8.470099e-01,1.418830e-06,5.617113e-10,4.434147e-01,5.756850e-09
133705,ENSG00000196867,ZFP28,AFR (exomes),4.697400e-01,1.182206e-01,3.597032e-161,6.203591e-09,NaN,6.203591e-09
72326,ENSG00000144647,POMGNT2,EST (genomes),5.030602e-09,8.624051e-01,7.151690e-10,8.018112e-09,NaN,8.018112e-09
16842,ENSG00000091181,IL5RA,AFR (genomes),3.223944e-09,9.845975e-01,1.277651e-09,8.063664e-09,NaN,8.063664e-09
109619,ENSG00000172349,IL16,EST (genomes),2.897549e-09,7.214742e-01,1.279629e-08,1.000444e-08,NaN,1.000444e-08
77615,ENSG00000149929,HIRIP3,AFR (exomes),4.463042e-09,9.981221e-03,1.693762e-07,1.087755e-08,NaN,1.087755e-08
77233,ENSG00000149527,PLCH2,AFR (exomes),4.512104e-09,6.017607e-01,1.316389e-06,1.180599e-08,NaN,1.180599e-08
96435,ENSG00000165392,WRN,EST (genomes),2.217039e-10,3.504896e-01,9.490622e-15,6.026867e-10,1.000000e+00,1.339750e-08
103884,ENSG00000169105,CHST14,AMR (exomes),2.024262e-08,3.465620e-01,1.502679e-07,2.062040e-08,NaN,2.062040e-08
74819,ENSG00000146830,GIGYF1,AFR (exomes),5.378857e-01,9.302510e-02,7.261763e-188,2.183641e-08,NaN,2.183641e-08
99681,ENSG00000166948,TGM6,EST (genomes),5.972928e-10,5.625398e-01,1.216247e-09,1.165535e-09,1.000000e+00,2.514070e-08
39015,ENSG00000116670,MAD2L2,AFR (genomes),2.130722e-08,2.093157e-01,4.252680e-07,2.563895e-08,NaN,2.563895e-08
24249,ENSG00000104147,OIP5,FIN (exomes),1.566099e-08,2.402216e-02,3.242426e-08,2.847937e-08,NaN,2.847937e-08
22609,ENSG00000102699,PARP4,AFR (exomes),1.376569e-08,6.932709e-01,9.979584e-08,3.864688e-08,NaN,3.864688e-08
72969,ENSG00000145214,DGKQ,EST (genomes),2.410120e-08,5.147281e-01,8.418680e-09,3.889140e-08,NaN,3.889140e-08
46473,ENSG00000124257,NEURL2,EST (genomes),2.828853e-08,5.131969e-01,9.739817e-07,4.130913e-08,NaN,4.130913e-08
34096,ENSG00000112280,COL9A1,EST (genomes),3.254159e-08,4.319662e-01,5.430831e-09,4.211260e-08,NaN,4.211260e-08
99223,ENSG00000166801,FAM111A,FIN (exomes),4.097093e-08,4.300763e-01,3.465458e-08,4.602097e-08,NaN,4.602097e-08
86090,ENSG00000159189,C1QC,EST (genomes),2.324902e-08,4.530864e-01,8.669730e-08,4.809582e-08,NaN,4.809582e-08
117986,ENSG00000178773,CPNE7,FIN (exomes),2.093722e-08,1.558756e-01,1.065290e-07,5.219481e-08,NaN,5.219481e-08
43208,ENSG00000120738,EGR1,AFR (exomes),1.948230e-08,1.451173e-01,3.542860e-06,5.246665e-08,NaN,5.246665e-08
29353,ENSG00000108018,SORCS1,EST (genomes),3.847723e-08,4.630079e-03,9.582352e-09,5.641713e-08,NaN,5.641713e-08
54218,ENSG00000131969,ABHD12B,AMR (exomes),8.316537e-08,2.409887e-01,4.301044e-05,6.336718e-08,NaN,6.336718e-08
56530,ENSG00000133800,LYVE1,EST (genomes),5.791717e-08,4.787158e-03,1.595150e-07,6.566678e-08,NaN,6.566678e-08
30757,ENSG00000109184,DCUN1D4,EAS (exomes),3.876195e-08,8.917958e-01,1.691929e-07,7.546473e-08,NaN,7.546473e-08
96948,ENSG00000165671,NSD1,ASJ (exomes),3.167096e-01,5.653057e-08,3.121316e-05,7.671317e-08,NaN,7.671317e-08
42009,ENSG00000119698,PPP4R4,EST (genomes),2.059693e-09,5.779550e-01,1.972991e-11,3.996129e-09,1.000000e+00,8.127304e-08
41962,ENSG00000119685,TTLL5,AFR (exomes),3.386675e-01,7.974430e-02,3.282332e-174,2.821998e-08,1.423767e-01,8.169334e-08
9473,ENSG00000070019,GUCY2C,AFR (exomes),2.455645e-09,9.170023e-01,1.784444e-08,4.173561e-09,1.000000e+00,8.470033e-08
32471,ENSG00000111052,LIN7A,AFR (genomes),3.459790e-09,2.838667e-01,5.761288e-01,8.014283e-09,5.494797e-01,8.913423e-08
143588,ENSG00000221989,OR2A2,AFR (exomes),1.033619e-07,8.246031e-01,5.852256e-07,9.108605e-08,NaN,9.108605e-08
63091,ENSG00000137824,RMDN3,AFR (exomes),3.769813e-09,6.944091e-01,2.894320e-08,5.922543e-09,1.000000e+00,1.181222e-07
95364,ENSG00000164756,SLC30A8,AFR (exomes),3.058345e-07,8.588275e-02,1.769701e-06,1.241888e-07,NaN,1.241888e-07
93637,ENSG00000164070,HSPA4L,FIN (exomes),2.598314e-09,9.821664e-08,8.034024e-05,6.503888e-09,1.000000e+00,1.291078e-07
52023,ENSG00000130227,XPO7,meta,5.796603e-01,7.773910e-01,1.381433e-07,8.058846e-01,9.009053e-09,1.433236e-07
63511,ENSG00000138039,LHCGR,FIN (exomes),5.299432e-08,7.469629e-02,8.817006e-09,3.791158e-08,2.002950e-01,1.495614e-07
60043,ENSG00000135972,MRPS9,AMR (exomes),5.036548e-09,1.135299e-01,2.290383e-06,1.472368e-08,5.185699e-01,1.503419e-07
90369,ENSG00000162775,RBM15,FIN (exomes),2.998878e-09,5.179126e-01,2.174568e-08,8.316142e-09,1.000000e+00,1.630385e-07
142576,ENSG00000214309,MBLAC1,AFR (genomes),8.707938e-09,3.587473e-01,3.359388e-07,1.367143e-08,6.105754e-01,1.636208e-07
93863,ENSG00000164116,GUCY1A1,AFR (exomes),9.379537e-08,1.823331e-01,1.266525e-06,1.665757e-07,NaN,1.665757e-07
63528,ENSG00000138061,CYP1B1,EST (genomes),3.614386e-09,3.529500e-01,3.264827e-08,8.778735e-09,1.000000e+00,1.716325e-07
14442,ENSG00000085274,MYNN,FIN (exomes),2.369936e-07,3.936271e-01,1.871827e-08,1.817351e-07,NaN,1.817351e-07
29900,ENSG00000108551,RASD1,AFR (genomes),7.879376e-08,4.688458e-02,7.108512e-06,1.827285e-07,NaN,1.827285e-07
147434,ENSG00000258986,TMEM179,EUR (exomes),9.617203e-08,4.595920e-01,8.255982e-05,1.980585e-07,NaN,1.980585e-07
60450,ENSG00000136197,C7orf25,FIN (exomes),1.723302e-07,8.305885e-01,3.237129e-09,2.231448e-07,NaN,2.231448e-07
81858,ENSG00000154556,SORBS2,ASJ (exomes),1.102385e-07,7.468735e-01,5.804424e-04,2.258027e-07,NaN,2.258027e-07
147532,ENSG00000259431,THTPA,AFR (genomes),9.292257e-09,1.722240e-01,1.221616e-07,1.189933e-08,1.000000e+00,2.290238e-07
100849,ENSG00000167608,TMC4,AFR (exomes),1.543363e-07,9.193231e-01,5.672216e-08,2.515619e-07,NaN,2.515619e-07
96913,ENSG00000165655,ZNF503,FIN (exomes),1.096369e-07,7.741260e-02,2.219197e-07,2.541684e-07,NaN,2.541684e-07
44730,ENSG00000122512,PMS2,FIN (exomes),1.321667e-07,3.557642e-01,1.600370e-08,2.613665e-07,NaN,2.613665e-07
10351,ENSG00000072422,RHOBTB1,EST (genomes),1.372514e-07,7.088332e-01,7.192109e-08,2.615028e-07,NaN,2.615028e-07
105096,ENSG00000169862,CTNND2,AFR (exomes),1.009022e-07,7.693505e-01,6.174401e-05,2.745492e-07,NaN,2.745492e-07
117830,ENSG00000178607,ERN1,EST (genomes),1.189906e-07,6.143758e-01,7.649338e-08,2.794578e-07,NaN,2.794578e-07
83846,ENSG00000156858,PRR14,EST (genomes),1.861186e-07,8.492151e-01,4.726688e-07,2.831937e-07,NaN,2.831937e-07
2201,ENSG00000010319,SEMA3G,EST (genomes),7.054908e-09,2.715964e-01,1.654436e-08,1.622643e-08,1.000000e+00,3.072737e-07
50493,ENSG00000128487,SPECC1,AFR (exomes),2.833484e-08,7.760967e-01,4.421615e-07,1.635066e-08,1.000000e+00,3.095015e-07
58125,ENSG00000134884,ARGLU1,EAS (exomes),7.873559e-07,1.256971e-02,2.880678e-06,3.221189e-07,NaN,3.221189e-07
68951,ENSG00000142102,PGGHG,FIN (exomes),8.139833e-09,3.545448e-01,3.507410e-08,1.800574e-08,1.000000e+00,3.390945e-07
118525,ENSG00000179148,ALOXE3,EST (genomes),8.478775e-09,2.063136e-01,9.487902e-08,1.817443e-08,1.000000e+00,3.421018e-07
128452,ENSG00000186834,HEXIM1,EST (genomes),1.622784e-07,6.119949e-01,2.528287e-08,3.461850e-07,NaN,3.461850e-07
98437,ENSG00000166377,ATP9B,AFR (exomes),6.527462e-09,1.211794e-02,8.295354e-07,1.856821e-08,1.000000e+00,3.491160e-07
45198,ENSG00000122971,ACADS,EST (genomes),1.726229e-07,1.573528e-01,9.699867e-10,3.564966e-07,NaN,3.564966e-07
47085,ENSG00000124772,CPNE5,EST (genomes),1.732752e-07,4.232323e-01,5.026441e-06,3.645107e-07,NaN,3.645107e-07
119648,ENSG00000180251,SLC9A4,FIN (exomes),9.966587e-09,4.227314e-01,3.638206e-08,2.416008e-08,1.000000e+00,4.478932e-07
134933,ENSG00000197532,OR6Y1,EAS (exomes),2.322316e-08,5.999032e-01,9.838052e-08,5.139929e-08,4.815703e-01,4.582739e-07
115226,ENSG00000176422,SPRYD4,AMR (exomes),9.625109e-09,5.868994e-01,4.079532e-06,2.560807e-08,1.000000e+00,4.732463e-07
88886,ENSG00000161940,BCL6B,AFR (exomes),2.950554e-07,6.167544e-01,2.950908e-07,4.784437e-07,NaN,4.784437e-07
8113,ENSG00000065457,ADAT1,AFR (exomes),2.143155e-07,7.056652e-01,3.955026e-06,5.006681e-07,NaN,5.006681e-07
84917,ENSG00000157933,SKI,EST (genomes),2.068788e-07,4.250964e-01,5.248892e-07,5.165601e-07,NaN,5.165601e-07
6285,ENSG00000054523,KIF1B,ASJ (exomes),5.733279e-07,9.767111e-01,3.187940e-02,5.424245e-07,NaN,5.424245e-07
23992,ENSG00000103811,CTSH,AMR (exomes),1.260559e-08,6.375445e-01,1.076638e-05,3.096907e-08,1.000000e+00,5.664329e-07
5635,ENSG00000049192,ADAMTS6,EST (genomes),3.941890e-07,2.874707e-01,1.705598e-07,5.801332e-07,NaN,5.801332e-07
83422,ENSG00000156304,SCAF4,SAS (exomes),3.101299e-07,6.420833e-01,3.421034e-06,6.182211e-07,NaN,6.182211e-07
125137,ENSG00000184661,CDCA2,AFR (exomes),1.600509e-07,5.887039e-01,4.600715e-06,6.290650e-07,NaN,6.290650e-07
109246,ENSG00000172146,OR1A1,FIN (exomes),6.539549e-08,1.732370e-01,5.887879e-07,1.743629e-07,2.002950e-01,6.345725e-07
120999,ENSG00000181634,TNFSF15,AFR (exomes),3.898223e-07,4.222933e-01,1.852210e-06,6.540497e-07,NaN,6.540497e-07
53914,ENSG00000131711,MAP1B,AFR (exomes),2.033946e-07,4.947485e-02,5.237627e-09,6.933921e-07,NaN,6.933921e-07
48150,ENSG00000125815,CST8,AMR (exomes),3.799194e-07,8.707761e-01,2.442320e-04,6.995829e-07,NaN,6.995829e-07
105497,ENSG00000170100,ZNF778,ASJ (exomes),4.934418e-07,3.180409e-01,9.133999e-05,8.248281e-07,NaN,8.248281e-07
69329,ENSG00000142530,GARIN5A,AMR (exomes),2.208657e-05,8.140965e-01,5.574894e-06,5.023232e-08,1.000000e+00,8.944672e-07
89913,ENSG00000162618,ADGRL4,FIN (exomes),2.520143e-08,5.454614e-01,4.915615e-08,5.043721e-08,1.000000e+00,8.979102e-07
136406,ENSG00000198182,ZNF607,FIN (exomes),3.898215e-07,8.784316e-01,2.139952e-08,4.949442e-07,1.057348e-01,9.297261e-07
134396,ENSG00000197256,KANK2,AFR (exomes),9.821563e-07,7.460582e-01,7.234131e-07,9.370972e-07,NaN,9.370972e-07
76190,ENSG00000148498,PARD3,AFR (exomes),4.963950e-01,7.558733e-02,2.485155e-158,9.756783e-07,NaN,9.756783e-07
41841,ENSG00000119608,PROX2,FIN (exomes),4.372145e-08,1.452007e-01,3.612137e-08,5.639772e-08,1.000000e+00,9.977228e-07
102925,ENSG00000168556,ING2,EUR-N (exomes),8.905396e-07,3.209583e-01,1.050624e-05,1.026664e-06,NaN,1.026664e-06
6437,ENSG00000055130,CUL1,meta,9.868763e-01,1.471510e-01,9.820566e-02,3.324482e-01,1.947415e-07,1.136398e-06
97331,ENSG00000165861,ZFYVE1,AFR (exomes),4.793477e-07,3.148629e-01,4.671062e-05,1.216511e-06,NaN,1.216511e-06
21511,ENSG00000101193,GID8,AMR (exomes),6.365748e-07,3.624872e-01,4.289668e-05,1.268393e-06,NaN,1.268393e-06
82666,ENSG00000155561,NUP205,EST (genomes),4.451214e-07,7.946150e-01,2.373581e-08,1.302381e-06,NaN,1.302381e-06
104312,ENSG00000169344,UMOD,AFR (exomes),9.251968e-07,3.700840e-01,6.538026e-06,1.456534e-06,NaN,1.456534e-06
119350,ENSG00000179930,ZNF648,FIN (exomes),7.635391e-07,4.324668e-01,1.636314e-07,1.463869e-06,NaN,1.463869e-06
26244,ENSG00000105486,LIG1,AFR (exomes),7.551700e-07,1.132456e-02,1.107453e-05,1.512500e-06,NaN,1.512500e-06
61650,ENSG00000136935,GOLGA1,AFR (exomes),8.169026e-07,1.605605e-01,2.396918e-05,1.530665e-06,NaN,1.530665e-06
44975,ENSG00000122735,DNAI1,AFR (exomes),1.031250e-06,9.801259e-01,2.305957e-05,1.530986e-06,NaN,1.530986e-06
138128,ENSG00000198890,PRMT6,AMR (exomes),4.419386e-07,2.092323e-01,1.558898e-04,1.554705e-06,NaN,1.554705e-06